application: yum2rss
version: 1
runtime: python
api_version: 1

handlers:

  - url: /remote_api
    script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
    login: admin

  - url: /rss
    script: rss.py

  - url: /(download|url_task|download_chunk_task|parse_xml_task|parse_repomd|parse_other)
    script: download.py
    login: admin

  - url: /
    static_files: static/index.html
    upload: static/index.html

  - url: /home/.*
    script: main.py
    login: required
