application: repo2rss
version: 1
runtime: python
api_version: 1

derived_file_type:
  - python_precompiled

handlers:

  - url: /remote_api
    script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
    login: admin

  - url: /rss
    script: rss.py

  - url: /(download|url_task|download_chunk_task|parse_xml_task)
    script: download.py
    login: admin
